---
# tasks file for gitlab
- name: Install dependent packages for Gitlab
      dnf:
        name: 
          - curl
          - policycoreutils
          - openssh-server
          - perl
          - postfix
        state: latest   

    - name: start firewalld service 
      systemd: 
        name: firewalld
        state: started
        enabled: yes 

    - name: set firwall services for http https
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: true
      loop: "{{ services }}"
      
    - name: set selinux to disable 
      selinux:
        state: disabled
     
    - name: check file exist 
      stat:
        path:  /etc/gitlab/gitlab.rb
      register: gitlab_server 

    - name: add gitlab repo
      shell: curl  https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash
      when: gitlab_server.stat.exists == false 

    - name: install gitlab packages
      dnf:
        name: gitlab-ee
        state: present
   


    - name: set url for gitlab
      shell: EXTERNAL_URL="https://gitlab.example.com"
      tags: set_url

