---
# tasks file for elasticsearch
    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  


    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive   

    - name: installing Java JDK 1.8.0-openjdk-devel
      dnf:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Create Elastic repo
      template:
        src: templates/elasticsearch.j2
        dest: /etc/yum.repos.d/elastic.repo 

    - name: install elasticsearch packages 
      dnf:
        name: elasticsearch
        state: present 

    - name: start enable elasticsearch
      systemd:
        name: elasticsearch     
        state: started
        enabled: yes
     
    - name: Installing filebeat
      dnf:
        name: filebeat
        state: present

     


    - name: Starting filebeat service
      systemd:
        name: filebeat
        state: started
        enabled: yes

    - name: install kibana
      dnf:
        name: kibana
        state: present

    - name: Enable and start Kibana
      systemd:
        name: kibana      
        state: started
        enabled: yes 


    - name: Opening Ports 5600 - 5601 for kibana.
      firewalld:
        port: 5600-5601/tcp
        permanent: yes
        state: enabled
        immediate: true

    - name: Opening Ports 9200 - 9400 for Elasticsearch.
      firewalld:
        port: 9200-9400/tcp
        permanent: yes
        state: enabled
        immediate: true
    - name: creating kibana log directory
      file:
        path: /var/log/kibana/
        state: directory
        mode: '0755'  

    - name: Updating configs for kibana
      template:
        src: templates/kibana.confi.j2
        dest:  /etc/kibana/kibana.yml
      notify: restart kibana


    - name: performing cluster configuration
      template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

